<div class="break-badge form-actions row-fluid">
    <?php if ($this->badge->getStatus() === Model_Badges::FREE): ?>
        <button data-name="allocate" data-id="<?php echo $this->badge->getId(); ?>" class="span3 btn btn-large btn-success sign-free">Freies Schild</button>
    <?php else: ?>
        <button data-name="deallocate" data-id="<?php echo $this->badge->getId(); ?>" class="span3 btn btn-large btn-danger sign-used">
            Belegt
            <?php if ($this->sSessionId === $this->badge->getSession()) { echo ' <i class="icon-user"></i>'; } ?>
        </button>
        <div class="span3 alert alert-warning">
            <strong>Rest-Zeit: <span data-limit="<?php echo $this->badgeConfig->duration; ?>" data-left="<?php echo $this->badge->getLeft(); ?>"><?php echo date('i:s', $this->badge->getLeft()); ?></span>&nbsp;Minuten</strong>
        </div>
    <?php endif;?>
</div>
