<div class="modal hide" id="badgeModal">
    <form id="modalForm" method="POST" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'manage'));?>">
        <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal">X</button>
           <h3>Bitte Passwort angeben!</h3>
        </div>
        <div class="modal-body">
            <input name="password" type="password" class="input-xlarge" placeholder="Passwort" />
        </div>
        <div class="modal-footer">
           <a href="#" class="btn" data-dismiss="modal">Schliessen</a>
           <a href="#" class="btn btn-primary save-modal">Speichern</a>
        </div>
    </form>
</div>