<!DOCTYPE html>
<html lang="de">
<head>
    <title><?php echo $this->sName; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->headMeta()->prependHttpEquiv('Content-Type', 'text/html; charset=utf-8')?>

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/css/bootstrap-combined.min.css" type="text/css" media="screen" />
    <style type="text/css">
        .break-badge .alert {margin-bottom:0}
    </style>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script type="text/javascript" src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('resource/base.js'); ?>"></script>
    <script type="text/javascript">
        var BASE_URL = "<?php echo $this->baseUrl('/') ?>";
    </script>
</head>
<body class="<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); echo $oRequest->getControllerName() . '_' . $oRequest->getActionName() ?>">
    <div class="container">
        <?php echo $this->layout()->content ?>
    </div>

    <?php echo $this->render('index/partial/modal.phtml');?>
</body>
</html>
