<!DOCTYPE html>
<html lang="de">
<head>
    <title><?php echo $this->sName; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->headMeta()->prependHttpEquiv('Content-Type', 'text/html; charset=utf-8')?>

    <link rel="stylesheet" href="<?php echo $this->baseUrl('resource/bootstrap.css'); ?>" type="text/css" media="screen" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('resource/bootstrap-responsive.css'); ?>" type="text/css" media="screen" />
    <style type="text/css">
        .break-badge .alert {margin-bottom:0}
    </style>
    <script type="text/javascript" src="<?php echo $this->baseUrl('resource/jquery-1.8.2.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('resource/bootstrap.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('resource/base.js'); ?>"></script>
    <script type="text/javascript">
        var BASE_URL = "<?php echo $this->baseUrl('/') ?>";
    </script>
</head>
<body class="<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); echo $oRequest->getControllerName() . '_' . $oRequest->getActionName() ?>">
    <div class="container">
        <?php echo $this->layout()->content ?>
    </div>

    <?php echo $this->render('index/partial/modal.phtml');?>
</body>
</html>
